sudo : required
services : 
      - docker 

before_install:
      - docker build -t pratikanand13/docker-react -f Dockerfile.dev .

script:
      - docker run pratikanand13/docker-react npm run test -- --coverage
      